version: 2
project_name: akmon

before:
  hooks:
    - go mod download

builds:
  - id: akmon
    main: ./cmd/monitor
    binary: akmon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}

archives:
  - id: akmon
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - SECURITY.md
      - config.yaml
      - src: bpf/monitor.bpf.o
        strip_parent: true
      - src: scripts/akmon.service
        strip_parent: true
      - src: scripts/logrotate.d/akmon
        dst: logrotate.akmon

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  draft: true
  prerelease: auto
  name_template: "v{{ .Version }}"
